"""Official Python SDK for Figranium."""

from ._async_resources import (
    AsyncCabinetsResource,
    AsyncCapturesResource,
    AsyncExecutionResource,
    AsyncExecutionsResource,
    AsyncHealthResource,
    AsyncSchedulesResource,
    AsyncTasksResource,
)
from ._resources import (
    CabinetsResource,
    CapturesResource,
    ExecutionResource,
    ExecutionsResource,
    HealthResource,
    SchedulesResource,
    TasksResource,
)
from .actions import Actions, action, actions, variable
from .client import AsyncFigranium, Figranium
from .templates import TemplatesResource, AsyncTemplatesResource
from .errors import FigraniumError
from .types import (
    Action,
    AiModels,
    AiProvider,
    BrowserSession,
    Cabinet,
    CabinetItem,
    CabinetItemStatus,
    CaptchaType,
    Capture,
    Credential,
    CredentialInput,
    ExecuteTaskOptions,
    Execution,
    ExecutionResult,
    ExtractionFormat,
    HealthStatus,
    HttpMethod,
    Proxy,
    ProxyInput,
    RequestOptions,
    Schedule,
    SelectorCandidate,
    StealthConfig,
    StreamEvent,
    Task,
    TaskMode,
    TaskOutcome,
    TaskOutput,
    TaskSummary,
    TaskVariable,
    TaskVersion,
    Theme,
    User,
)

__all__ = [
    "TemplatesResource",
    "AsyncTemplatesResource",
    "Action",
    "Actions",
    "AiModels",
    "AiProvider",
    "AsyncCabinetsResource",
    "AsyncCapturesResource",
    "AsyncExecutionResource",
    "AsyncExecutionsResource",
    "AsyncFigranium",
    "AsyncHealthResource",
    "AsyncSchedulesResource",
    "AsyncTasksResource",
    "BrowserSession",
    "Cabinet",
    "CabinetItem",
    "CabinetItemStatus",
    "CabinetsResource",
    "CaptchaType",
    "Capture",
    "CapturesResource",
    "Credential",
    "CredentialInput",
    "ExecuteTaskOptions",
    "Execution",
    "ExecutionResource",
    "ExecutionResult",
    "ExecutionsResource",
    "ExtractionFormat",
    "Figranium",
    "FigraniumError",
    "HealthStatus",
    "HealthResource",
    "HttpMethod",
    "Proxy",
    "ProxyInput",
    "RequestOptions",
    "Schedule",
    "SchedulesResource",
    "SelectorCandidate",
    "StealthConfig",
    "StreamEvent",
    "Task",
    "TaskMode",
    "TaskOutcome",
    "TaskOutput",
    "TaskSummary",
    "TaskVariable",
    "TaskVersion",
    "TasksResource",
    "Theme",
    "User",
    "action",
    "actions",
    "variable",
]

__version__ = "0.3.0"
